services:
  # React Frontend Service
  web:
    build: ./web
    ports:
      - "8080:8080"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
      - ./web/index.html:/app/index.html
      - ./web/vite.config.ts:/app/vite.config.ts
      - ./web/tailwind.config.ts:/app/tailwind.config.ts
      - ./web/postcss.config.js:/app/postcss.config.js
      - ./web/tsconfig.json:/app/tsconfig.json
      - ./web/tsconfig.app.json:/app/tsconfig.app.json
      - ./web/tsconfig.node.json:/app/tsconfig.node.json
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

  # FastAPI Backend Service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Celery Worker Service
  worker:
    build: .
    command: celery -A api.worker:celery_app worker --loglevel=info
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # Celery Beat Scheduler Service (New)
  beat:
    build: .
    command: celery -A api.worker:celery_app beat --loglevel=info -s /tmp/celerybeat-schedule
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
