services:
  # FastAPI Backend Service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    environment:
      - POSTGRES_DB_TEST=holdingsview_test
    depends_on:
      - db
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: