services:
  api:
    image: "orhershko/holdingsview-api:latest"
    ports:
      - "80:8000"
    mem_limit: 256m

  worker:
    image: "orhershko/holdingsview-worker:latest"
    command: ["celery", "-A", "api.worker.celery_app", "worker", "--loglevel=info"]
    mem_limit: 256m