services:
  # FastAPI Backend Service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Celery Worker Service
  worker:
    build: .
    command: celery -A api.worker:celery_app worker --loglevel=info
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # Celery Beat Scheduler Service (New)
  beat:
    build: .
    command: celery -A api.worker:celery_app beat --loglevel=info -s /tmp/celerybeat-schedule
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
