"""Add portfolio_snapshot table

Revision ID: 5c7a8b9e4d3f
Revises: 4b1e7c9f8a2d
Create Date: 2025-06-16 10:00:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7a8b9e4d3f'
down_revision: Union[str, None] = '4b1e7c9f8a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfoliosnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_market_value', sa.Float(), nullable=False),
    sa.Column('total_cost_basis', sa.Float(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfoliosnapshot_date'), 'portfoliosnapshot', ['date'], unique=False)
    op.create_index(op.f('ix_portfoliosnapshot_id'), 'portfoliosnapshot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfoliosnapshot_id'), table_name='portfoliosnapshot')
    op.drop_index(op.f('ix_portfoliosnapshot_date'), table_name='portfoliosnapshot')
    op.drop_table('portfoliosnapshot')
    # ### end Alembic commands ###