"""add watchlist item table

Revision ID: a43be1db52e4
Revises: f06076a827ee
Create Date: 2025-06-28 23:00:39.487090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a43be1db52e4'
down_revision: Union[str, None] = 'f06076a827ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_item_id'), 'watchlist_item', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_item_symbol'), 'watchlist_item', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_item_symbol'), table_name='watchlist_item')
    op.drop_index(op.f('ix_watchlist_item_id'), table_name='watchlist_item')
    op.drop_table('watchlist_item')
    # ### end Alembic commands ###
